# Site settings
title: opensource.seapagan.net
tagline: Open source on GitHub.
email: seapagan@gmail.com
description: >
  Open Source Ruby Gem GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://confoog.seapagan.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#highlighter: pygments

exclude: [README.md, Gemfile, Gemfile.lock]
